version: '3.9'

services:
    mariadb:
      image: mariadb:10.7
      ports:
        - 3307:3306
      container_name: "database"
      volumes:
        - ~/apps/mariadb:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=123456789
        - MYSQL_PASSWORD=123456789
        - MYSQL_USER=prueba01
        - MYSQL_DATABASE=indicadores
      
      network_mode: default

      restart: always


    app:
        build:
          context: app/

        container_name: appPrueba

        
        restart: 'always'
        
        network_mode: "default"
        

    
    server:
        build:
          context: server/
          args:
            - DATABASE_IP=$DATABASE_IP 
          
        container_name:  serverPrueba
        
        
        restart: 'always'
        network_mode: "default"