version: '3.8'
services:
  mysql:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: databaseP1
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_PASSWORD: "123456789"
    volumes:
      -./ schemas:/var/lib/mysql:rw
    networks:
        mysql_network:
          aliases:
            - mysql_host
  
  volumes: 
    schemas: {}
  networks:
    mysql_network:
      name: mysql_net
      driver: bridge

    